#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/home/moreno/Desktop/moreno/workspace/ProvaJNI/jni/ABE-Dependencies/android-toolchain/bin/arm-linux-androideabi-gcc-4.6 -march=armv7-a -mfloat-abi=softfp --sysroot=/home/moreno/android-ndk-r9d/platforms/android-9/arch-arm -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android-armv7"
  #define DATE "Wed Oct 15 18:18:33 CEST 2014"
#endif
